# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

name: 'Template Action'
description: 'Project Template for Deno GitHub Actions.'
author: 'Author'
branding:
  icon: 'award'
  color: 'green'

inputs:
  custom-input:
    description: 'This is the description for a custom input.'
    default: 'DefaultValue'
    required: false

outputs:
  custom-output:
    description: 'This is the description for a custom output.'

runs:
  using: 'docker'
  image: 'denoland/deno:latest'
  entrypoint: 'dist/bundle.min.js'
