name: 'Template Deno GitHub Actions'
description: 'Project Template for Deno GitHub Actions.'
author: 'Author'
inputs:
  custom-input:
    description: 'Description.'
    default: 'DefaultValue'
    required: false

outputs:
  custom-output:
    description: 'Description.'

runs:
  using: 'node20'
  main: 'dist/bundle.min.js'
