name: 'Test Action'

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test-action:
    name: 'Test Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4
      
      - name: 'Test Action'
        id: test
        uses: './'
        with:
          custom-input: 'Test123'
      
      - name: 'Output Test'
        run: |
          echo "Custom Output: ${{ steps.test.outputs.custom-output }}"

