name: 'Test Action'

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: 'Test Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4
      
      - name: 'Setup Deno'
        uses: denoland/setup-deno@v2

      - name: 'Build Action'
        run: |
          deno task build
      
      - name: 'Test Action'
        uses: './'
        with:
          custom-input: 'Test123'
